apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: z0yoo4tep-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-nodejs:5f0ac4202954dde21b83f99ebfac347cf38bf86a@sha256:b06c685496a5e48095845b0241ca79bec12ab0e5aceda38cdb90b8aa5c6c4e26
          name: container-image
